### ISSUE TITLE
Downloading/uploading files freezes the entire app

### ISSUE THREAD

**Issue by SpeckyYT** [0xb-s/ssh-browser#18]
All SSH commands should run on separate threads or asyncronously, so that the app doesn't entirely freeze.

If this gets implemented, some sort of window which shows what commands are currently running would be quite nice (with maybe progress percentage if possible).

**Comment by 0xb-s** [comment]
> All SSH commands should run on separate threads or asyncronously, so that the app doesn't entirely freeze.

Thanks for letting me know. I’ll fix this

**Comment by 0xb-s** [comment]
> If this gets implemented, some sort of window which shows what commands are currently running would be quite nice (with maybe progress percentage if possible).

Could you share an example or a mock-up so I can better understand what you’re envisioning?

Althrought this would be seperate pr
