### ISSUE TITLE
UI improvements (file browser)

### ISSUE THREAD

**Issue by SpeckyYT** [0xb-s/ssh-browser#5]
- [x] Folders, instead of [DIR] should have a folder emoji or any other way to represent that it's a folder.
- [x] Files could have a square appearance, kind a like windows file explorer
 - [ ] Instead of cluttering the screen with Download / Delete / Modify buttons, make put them into a context window (right click)

**Comment by 0xb-s** [comment]
For Task 3, I feel the current implementation works well and I’m not sure it needs to be changed right now.  I’d suggest revisiting this in the future if we decide to support multiple options, as it could be more relevant then.
